# Generated by Django 2.1.2 on 2019-12-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='サンプル項目1 文字列'),
        ),
    ]
