# Generated by Django 2.1.2 on 2019-12-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191225_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='test_id',
            field=models.IntegerField(blank=True, choices=[(1, '選択１'), (2, '選択２'), (3, '選択３'), (4, '選択４'), (5, '選択５')], null=True, verbose_name='サンプル'),
        ),
    ]
